In [1]:
import numpy as np

In [5]:
arr = np.arange(0,20)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
arr[5]

5

In [8]:
arr[4:7]

array([4, 5, 6])

In [11]:
arr[4:7] = 20
arr

array([ 0,  1,  2,  3, 20, 20, 20,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
slice = arr[2:8]

slice[:] = 150
slice

array([150, 150, 150, 150, 150, 150])

In [20]:
arr2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
arr2D[2] [2]

9

In [25]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2D[:2, 0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr + arr

array([  0,   2, 300, 300, 300, 300, 300, 300,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38])

In [27]:
np.sqrt(arr)

array([ 0.        ,  1.        , 12.24744871, 12.24744871, 12.24744871,
       12.24744871, 12.24744871, 12.24744871,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894])